export const TYPES = {
  GameEntryFactory: Symbol.for('GameEntry'),
  Engine2d: Symbol.for('Engine2d'),
  Engine3d: Symbol.for('Engine3d'),
  UpdateEngine: Symbol.for('UpdateEngine'),
  App: Symbol.for('App'),
  MainScene2d: Symbol.for('MainScene2d'),
  MainScene3d: Symbol.for('MainScene3d'),
  Scenes2dGetter: Symbol.for('Scenes2dCollection'),
  AssetLoader3d: Symbol.for('AssetLoader3d'),
  AssetLoader2d: Symbol.for('AssetLoader2d'),
  AssetLoadersManager: Symbol.for('AssetLoadersManager'),
  Game: Symbol.for('Game'),
  Decorations3dCollection: Symbol.for('Decorations3dCollection'),
  Decorations3dManager: Symbol.for('Decorations3dManager'),
};
